import {
  ActivityLog,
  Channel,
  FileItem,
  Message,
  NotificationItem,
  Organization,
  OrganizationMember,
  Project,
  Task,
  UserProfile,
} from '@/types';

export const MOCK_PROFILES: UserProfile[] = [
  {
    id: 'usr-1',
    email: 'alex.rivera@acme.com',
    full_name: 'Alex Rivera',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    job_title: 'Head of Product',
    department: 'Product',
  },
  {
    id: 'usr-2',
    email: 'sarah.chen@acme.com',
    full_name: 'Sarah Chen',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    job_title: 'Senior Project Manager',
    department: 'Operations',
  },
  {
    id: 'usr-3',
    email: 'marcus.vance@acme.com',
    full_name: 'Marcus Vance',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    job_title: 'Lead Full-Stack Engineer',
    department: 'Engineering',
  },
  {
    id: 'usr-4',
    email: 'elena.rodriguez@acme.com',
    full_name: 'Elena Rodriguez',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    job_title: 'UI/UX Designer',
    department: 'Design',
  },
  {
    id: 'usr-5',
    email: 'david.kim@nexus.com',
    full_name: 'David Kim',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    job_title: 'Quality Assurance Lead',
    department: 'QA',
  },
];

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-acme',
    name: 'Acme Global Corp',
    slug: 'acme-corp',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    google_drive_folder_id: 'drive-folder-acme-101',
    created_at: '2026-01-15T08:00:00Z',
  },
];

export const MOCK_ORG_MEMBERS: OrganizationMember[] = [
  { id: 'mem-1', org_id: 'org-acme', user_id: 'usr-1', role: 'Admin', user: MOCK_PROFILES[0] },
  { id: 'mem-2', org_id: 'org-acme', user_id: 'usr-2', role: 'Project Manager', user: MOCK_PROFILES[1] },
  { id: 'mem-3', org_id: 'org-acme', user_id: 'usr-3', role: 'Member', user: MOCK_PROFILES[2] },
  { id: 'mem-4', org_id: 'org-acme', user_id: 'usr-4', role: 'Member', user: MOCK_PROFILES[3] },
  { id: 'mem-5', org_id: 'org-acme', user_id: 'usr-5', role: 'Viewer', user: MOCK_PROFILES[4] },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-101',
    org_id: 'org-acme',
    title: 'Cloud Infrastructure Migration',
    description: 'Migrating legacy monolith servers to Kubernetes clusters on Google Cloud Platform with automated CI/CD pipelines.',
    status: 'active',
    priority: 'urgent',
    due_date: '2026-09-15T00:00:00Z',
    created_by: 'usr-1',
    created_at: '2026-07-01T10:00:00Z',
    task_count: 14,
    completed_task_count: 9,
    members: [MOCK_PROFILES[0], MOCK_PROFILES[1], MOCK_PROFILES[2]],
  },
  {
    id: 'proj-102',
    org_id: 'org-acme',
    title: 'NextGen Mobile Banking App',
    description: 'Redesigning the iOS and Android native experience with biometric authentication and real-time expense analytics.',
    status: 'active',
    priority: 'high',
    due_date: '2026-10-30T00:00:00Z',
    created_by: 'usr-2',
    created_at: '2026-07-10T12:30:00Z',
    task_count: 22,
    completed_task_count: 11,
    members: [MOCK_PROFILES[1], MOCK_PROFILES[3], MOCK_PROFILES[4]],
  },
  {
    id: 'proj-103',
    org_id: 'org-acme',
    title: 'AI Customer Support Suite',
    description: 'Integration of LLM agents for automated resolution of Tier-1 support tickets and ticket routing.',
    status: 'planning',
    priority: 'medium',
    due_date: '2026-11-20T00:00:00Z',
    created_by: 'usr-1',
    created_at: '2026-08-01T09:15:00Z',
    task_count: 8,
    completed_task_count: 2,
    members: [MOCK_PROFILES[0], MOCK_PROFILES[2]],
  },
  {
    id: 'proj-104',
    org_id: 'org-acme',
    title: 'SOC2 Security Audit & Compliance',
    description: 'Preparing internal controls, encryption standards, and audit documentation for annual SOC2 Type II certification.',
    status: 'completed',
    priority: 'high',
    due_date: '2026-08-01T00:00:00Z',
    created_by: 'usr-2',
    created_at: '2026-05-15T08:00:00Z',
    task_count: 18,
    completed_task_count: 18,
    members: [MOCK_PROFILES[1], MOCK_PROFILES[2], MOCK_PROFILES[4]],
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    project_id: 'proj-101',
    project_title: 'Cloud Infrastructure Migration',
    title: 'Setup Helm charts for microservices deployment',
    description: 'Configure standard values.yaml and secrets encryption via SealedSecrets for GCP staging environment.',
    status: 'in_progress',
    priority: 'high',
    due_date: '2026-08-14T00:00:00Z',
    assigned_to: 'usr-3',
    assignee: MOCK_PROFILES[2],
    created_by: 'usr-2',
    created_at: '2026-08-02T10:00:00Z',
  },
  {
    id: 'task-2',
    project_id: 'proj-101',
    project_title: 'Cloud Infrastructure Migration',
    title: 'Configure Terraform IAM roles and bucket policies',
    description: 'Restrict access to production state files to authorized CI service accounts only.',
    status: 'done',
    priority: 'urgent',
    due_date: '2026-08-05T00:00:00Z',
    assigned_to: 'usr-3',
    assignee: MOCK_PROFILES[2],
    created_by: 'usr-1',
    created_at: '2026-07-28T09:00:00Z',
  },
  {
    id: 'task-3',
    project_id: 'proj-102',
    project_title: 'NextGen Mobile Banking App',
    title: 'Finalize Figma design tokens and dark mode palette',
    description: 'Ensure color contrast meets WCAG 2.1 AA accessibility guidelines across all primary screens.',
    status: 'in_review',
    priority: 'medium',
    due_date: '2026-08-11T00:00:00Z',
    assigned_to: 'usr-4',
    assignee: MOCK_PROFILES[3],
    created_by: 'usr-2',
    created_at: '2026-08-01T14:20:00Z',
  },
  {
    id: 'task-4',
    project_id: 'proj-102',
    project_title: 'NextGen Mobile Banking App',
    title: 'Implement FaceID / TouchID biometric login hook',
    description: 'Integrate React Native Keychain and LocalAuthentication for biometrics prompt on launch.',
    status: 'todo',
    priority: 'high',
    due_date: '2026-08-20T00:00:00Z',
    assigned_to: 'usr-3',
    assignee: MOCK_PROFILES[2],
    created_by: 'usr-2',
    created_at: '2026-08-04T11:00:00Z',
  },
  {
    id: 'task-5',
    project_id: 'proj-103',
    project_title: 'AI Customer Support Suite',
    title: 'Benchmark OpenAI GPT-4o response latency',
    description: 'Evaluate streaming response times and token costs for multi-turn support conversations.',
    status: 'backlog',
    priority: 'low',
    due_date: '2026-09-01T00:00:00Z',
    assigned_to: 'usr-1',
    assignee: MOCK_PROFILES[0],
    created_by: 'usr-1',
    created_at: '2026-08-06T15:00:00Z',
  },
];

export const MOCK_FILES: FileItem[] = [
  {
    id: 'file-1',
    org_id: 'org-acme',
    project_id: 'proj-101',
    project_title: 'Cloud Infrastructure Migration',
    google_drive_id: '1A2b3C4d5E6F7G8H9I0J',
    file_name: 'Kubernetes_Cluster_Architecture_v2.pdf',
    file_size: 4520000,
    mime_type: 'application/pdf',
    web_view_link: 'https://drive.google.com/file/d/1A2b3C4d5E6F7G8H9I0J/view',
    uploaded_by: 'usr-3',
    uploader: MOCK_PROFILES[2],
    created_at: '2026-08-03T11:45:00Z',
  },
  {
    id: 'file-2',
    org_id: 'org-acme',
    project_id: 'proj-102',
    project_title: 'NextGen Mobile Banking App',
    google_drive_id: '2B3c4D5e6F7g8H9i0J1K',
    file_name: 'Mobile_Design_System_Specs.fig',
    file_size: 18400000,
    mime_type: 'application/figma',
    web_view_link: 'https://drive.google.com/file/d/2B3c4D5e6F7g8H9i0J1K/view',
    uploaded_by: 'usr-4',
    uploader: MOCK_PROFILES[3],
    created_at: '2026-08-04T16:10:00Z',
  },
  {
    id: 'file-3',
    org_id: 'org-acme',
    project_id: 'proj-104',
    project_title: 'SOC2 Security Audit & Compliance',
    google_drive_id: '3C4d5E6f7G8h9I0j1K2L',
    file_name: 'SOC2_Type2_Audit_Report_2026.docx',
    file_size: 2100000,
    mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    web_view_link: 'https://drive.google.com/file/d/3C4d5E6f7G8h9I0j1K2L/view',
    uploaded_by: 'usr-2',
    uploader: MOCK_PROFILES[1],
    created_at: '2026-08-01T09:30:00Z',
  },
];

export const MOCK_CHANNELS: Channel[] = [
  { id: 'chan-1', org_id: 'org-acme', name: 'general', description: 'Company-wide announcements and team discussions', is_private: false, unread_count: 2 },
  { id: 'chan-2', org_id: 'org-acme', project_id: 'proj-101', name: 'proj-cloud-infra', description: 'Channel dedicated to K8s migration updates', is_private: false, unread_count: 0 },
  { id: 'chan-3', org_id: 'org-acme', project_id: 'proj-102', name: 'proj-mobile-banking', description: 'Design and iOS/Android sync channel', is_private: false, unread_count: 5 },
  { id: 'chan-4', org_id: 'org-acme', name: 'leadership-private', description: 'Executive level discussions', is_private: true, unread_count: 0 },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    channel_id: 'chan-1',
    sender_id: 'usr-1',
    sender: MOCK_PROFILES[0],
    content: 'Welcome everyone to the new Q3 PMS dashboard! Google Drive sync is now live for all project attachments.',
    created_at: '2026-08-07T09:00:00Z',
  },
  {
    id: 'msg-2',
    channel_id: 'chan-1',
    sender_id: 'usr-2',
    sender: MOCK_PROFILES[1],
    content: 'Great update Alex! I have linked the latest SOC2 report in the #general file repository.',
    created_at: '2026-08-07T09:12:00Z',
  },
  {
    id: 'msg-3',
    channel_id: 'chan-2',
    sender_id: 'usr-3',
    sender: MOCK_PROFILES[2],
    content: 'Helm charts deployment for GCP staging is ready for review. Pull request link is attached.',
    created_at: '2026-08-08T10:30:00Z',
  },
];

export const MOCK_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act-1',
    org_id: 'org-acme',
    project_id: 'proj-101',
    user_id: 'usr-3',
    user: MOCK_PROFILES[2],
    action: 'updated task status to In Progress',
    entity_type: 'task',
    entity_id: 'task-1',
    entity_title: 'Setup Helm charts for microservices deployment',
    created_at: '2026-08-08T10:30:00Z',
  },
  {
    id: 'act-2',
    org_id: 'org-acme',
    project_id: 'proj-102',
    user_id: 'usr-4',
    user: MOCK_PROFILES[3],
    action: 'uploaded file to Google Drive',
    entity_type: 'file',
    entity_id: 'file-2',
    entity_title: 'Mobile_Design_System_Specs.fig',
    created_at: '2026-08-07T16:10:00Z',
  },
  {
    id: 'act-3',
    org_id: 'org-acme',
    project_id: 'proj-101',
    user_id: 'usr-2',
    user: MOCK_PROFILES[1],
    action: 'created new project',
    entity_type: 'project',
    entity_id: 'proj-101',
    entity_title: 'Cloud Infrastructure Migration',
    created_at: '2026-08-06T09:15:00Z',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'usr-1',
    org_id: 'org-acme',
    title: 'Task Assigned',
    message: 'Sarah Chen assigned you to "Benchmark OpenAI GPT-4o response latency"',
    link: '/tasks',
    is_read: false,
    created_at: '2026-08-08T08:00:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'usr-1',
    org_id: 'org-acme',
    title: 'New Channel Message',
    message: 'Marcus Vance posted in #proj-cloud-infra',
    link: '/channels/chan-2',
    is_read: true,
    created_at: '2026-08-07T14:20:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'usr-1',
    org_id: 'org-acme',
    title: 'Google Drive File Uploaded',
    message: 'Elena Rodriguez attached Mobile_Design_System_Specs.fig to NextGen Mobile App',
    link: '/files',
    is_read: false,
    created_at: '2026-08-06T16:15:00Z',
  },
];
